### ISSUE TITLE
Help with installation

### ISSUE THREAD

**Issue by je223xa** [gabbysHub/matrix-webhook#1]
Hello there,
first of all thanks for writing this. I got into the whole matrix game recently and your project looks like a nice and good solution for simple webhooks

Sadly, I cannot get it to work. Maybe I just don't understand the documentation, or maybe there is a slight chance it helps you, or others who try it too.

## The steps I took were:
1. Clone your repo
2. create a user `hook1` with a password
3. Store both in the env file
4. Create a new room with my "normal" user and add the user hook1 to it. I named the room "webhook"
5. Configure env file to use `MATRIX_ADMIN_ROOM=!webhook:matrix.mydomain.org`
6. Run everything with `./build-sh`
And now I don't understand the logs anymore
```
matrix-webhook  | Starting the Python app...
matrix-webhook  | 2024-06-25 21:25:01,612 | INFO | module:root | Logging in using stored credentials.
matrix-webhook  | 2024-06-25 21:25:01,657 | INFO | module:root | The web server is waiting for events.
matrix-webhook  | 2024-06-25 21:25:02,353 | INFO | module:root | The Matrix client is waiting for events.
matrix-webhook  | 2024-06-25 21:25:02,457 | INFO | module:nio.client.base_client | New joined room !SnckBOBwICNSxFZvff:matrix.mydomain.org
```
why is it joining a random room and not the one I told it to? There is no welcome message in the "webhook" room

finally, after a few messages, the container exits with 
```
matrix-webhook  | 2024-06-25 21:25:02,462 | INFO | module:root | We synced, token: XXX
```

## debug logs
I have checked the python debug logs and it does seem to connect to the server
```
matrix-webhook  | 2024-06-25 21:49:39,533 | INFO | module:root | The Matrix client is waiting for events.
matrix-webhook  | 2024-06-25 21:49:39,614 | DEBUG | module:nio.responses | Validating response schema {...
```
in the reponse schema I can see my "normal" user, so it must be able to find something. I am guessing that it does connect and the `SnckBOBwICNSxFZvff` room is just some kind of hash?

## env file
My full env file is
```
MESSAGE_FORMAT=yaml
USE_MARKDOWN=False
ALLOW_UNICODE=True
DISPLAY_APP_NAME=True

MATRIX_SERVER=https://matrix.mydomain.org
MATRIX_SSLVERIFY=True
MATRIX_USERID=@hook1:matrix.mydomain.org
MATRIX_PASSWORD='secret'
MATRIX_DEVICE=docker
MATRIX_ADMIN_ROOM=!webhook:matrix.mydomain.org

KNOWN_TOKENS='YOURSECRETTOKEN,!webhook:matrix.mydomain.org,Curl'
```

Could you help me to try to figure out the problems? Sorry in advance if its some easy fix that I either didnt think about or did not read properly in your documentation

**Comment by gabbysHub** [comment]
Hi Jonny,

Based on your steps taken everything looks fine, but the only mistake I see
it is related to your environment file setup, on the
`MATRIX_ADMIN_ROOM=!webhook:matrix.mydomain.org` and
`KNOWN_TOKENS='YOURSECRETTOKEN,!webhook:matrix.mydomain.org,Curl'`.

Maybe I should specify that is should be the ROOM ID, not the room name.
Indeed would look something similar like you found in your logs
`!SnckBOBwICNSxFZvff:matrix.mydomain.org` which is the room ID, and because
the user `hook1` is already there (added by you) it joins the room when the
hook is running.

Using Element client in browser and entering the room, you can see the room
id in the URL, or alternatively, in the Element app, you can press `Invite
to this room` and when the window opens, on the top side click on `share
this room` which will give you the ROOM ID link.

Your `env` file should look like this, assuming `!SnckBOBwICNSxFZvff:
matrix.mydomain.org` is your ROOM ID

`MESSAGE_FORMAT=yaml

USE_MARKDOWN=False
ALLOW_UNICODE=True
DISPLAY_APP_NAME=True

MATRIX_SERVER=https://matrix.mydomain.org
MATRIX_SSLVERIFY=True
***@***.***:matrix.mydomain.org
MATRIX_PASSWORD='secret'
MATRIX_DEVICE=docker
MATRIX_ADMIN_ROOM=!SnckBOBwICNSxFZvff:matrix.mydomain.org

KNOWN_TOKENS='YOURSECRETTOKEN,!SnckBOBwICNSxFZvff:matrix.mydomain.org,Curl'`

Let me know this helps!

În mie., 26 iun. 2024 la 00:03, Jonny Ebinger ***@***.***> a
scris:

**Comment by gabbysHub** [comment]
Hi Jonny,

Based on your steps taken everything looks fine, but the only mistake I see
it is related to your environment file setup, on the
`MATRIX_ADMIN_ROOM=!webhook:matrix.mydomain.org` and
`KNOWN_TOKENS='YOURSECRETTOKEN,!webhook:matrix.mydomain.org,Curl'`.

Maybe I should specify that is should be the ROOM ID, not the room name.

Indeed, would look something similar with what you found in your logs `!SnckBOBwICNSxFZvff:matrix.mydomain.org` which is the room ID. 
Because the user `hook1` is already there (added by you), it joins the room when the hook is running.

Using Element client in browser and entering the room, you can see the room id in the URL, or alternatively, in the Element app, you can press `Invite to this room` and when the window opens, on the top side click on `share this room` which will give you the ROOM ID link.

Your `env` file should look like this, assuming `!SnckBOBwICNSxFZvff:matrix.mydomain.org` is your ROOM ID
```
MESSAGE_FORMAT=yaml

USE_MARKDOWN=False
ALLOW_UNICODE=True
DISPLAY_APP_NAME=True

MATRIX_SERVER=https://matrix.mydomain.org
MATRIX_SSLVERIFY=True
MATRIX_USERID=@hook1:matrix.mydomain.org
MATRIX_PASSWORD='secret'
MATRIX_DEVICE=docker
MATRIX_ADMIN_ROOM=!SnckBOBwICNSxFZvff:matrix.mydomain.org

KNOWN_TOKENS='YOURSECRETTOKEN,!SnckBOBwICNSxFZvff:matrix.mydomain.org,Curl'
```

Let me know this helps!

**Comment by je223xa** [comment]
Hey,
yes this fixed the issue! Thanks a lot now I can play around with it!
